/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package foo;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author grant
 */
public class SketchPad extends javax.swing.JFrame {
    
    /**
     * Creates new form SketchPad
     */
    public SketchPad() {
        initComponents();
        getContentPane().setBackground( new java.awt.Color( 153, 255, 0 ) );
        ButtonGroup drawingElementsGroup  = new ButtonGroup();
        drawingElementsGroup.add(freehandRadio);
        drawingElementsGroup.add(lineRadio);
        drawingElementsGroup.add(filledRectangleRadio);
        drawingElementsGroup.add(closedRectangleRadio);
        drawingElementsGroup.add(circleRadio);
        drawingElementsGroup.add(starRadio);
        freehandRadio.isSelected();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mySketchPanel = new foo.SketchPanel();
        setPenColorButton = new javax.swing.JButton();
        clearScreenButton = new javax.swing.JButton();
        itemPicker = new javax.swing.JPanel();
        freehandRadio = new javax.swing.JRadioButton();
        lineRadio = new javax.swing.JRadioButton();
        filledRectangleRadio = new javax.swing.JRadioButton();
        closedRectangleRadio = new javax.swing.JRadioButton();
        circleRadio = new javax.swing.JRadioButton();
        starRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout mySketchPanelLayout = new javax.swing.GroupLayout(mySketchPanel);
        mySketchPanel.setLayout(mySketchPanelLayout);
        mySketchPanelLayout.setHorizontalGroup(
            mySketchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mySketchPanelLayout.setVerticalGroup(
            mySketchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        setPenColorButton.setText("Set Pen Color");
        setPenColorButton.setToolTipText("Set the pn color of your choice");
        setPenColorButton.setFocusPainted(false);
        setPenColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPenColorButtonActionPerformed(evt);
            }
        });

        clearScreenButton.setText("Clear");
        clearScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearScreenButtonActionPerformed(evt);
            }
        });

        itemPicker.setBorder(javax.swing.BorderFactory.createTitledBorder("Drawing Elements"));

        freehandRadio.setText("Freehand");
        freehandRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freehandRadioActionPerformed(evt);
            }
        });

        lineRadio.setText("Line");
        lineRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineRadioActionPerformed(evt);
            }
        });

        filledRectangleRadio.setText("Open Rectangle");
        filledRectangleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filledRectangleRadioActionPerformed(evt);
            }
        });

        closedRectangleRadio.setText("Filled Rectangle");
        closedRectangleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closedRectangleRadioActionPerformed(evt);
            }
        });

        circleRadio.setText("Cirle");

        starRadio.setText("Star");

        javax.swing.GroupLayout itemPickerLayout = new javax.swing.GroupLayout(itemPicker);
        itemPicker.setLayout(itemPickerLayout);
        itemPickerLayout.setHorizontalGroup(
            itemPickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPickerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(itemPickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(starRadio)
                    .addComponent(circleRadio)
                    .addComponent(closedRectangleRadio)
                    .addComponent(filledRectangleRadio)
                    .addComponent(lineRadio)
                    .addComponent(freehandRadio))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        itemPickerLayout.setVerticalGroup(
            itemPickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPickerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(freehandRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filledRectangleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closedRectangleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(starRadio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mySketchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(itemPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(setPenColorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearScreenButton)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mySketchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(itemPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setPenColorButton)
                    .addComponent(clearScreenButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setPenColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPenColorButtonActionPerformed
        Color selectedColor = JColorChooser.showDialog(
                mySketchPanel, "Choose pen color", Color.BLACK );
        if ( selectedColor != null )
            mySketchPanel.setPenColor( selectedColor );
        
    }//GEN-LAST:event_setPenColorButtonActionPerformed

    private void clearScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearScreenButtonActionPerformed
        mySketchPanel.clear();
        repaint();
    }//GEN-LAST:event_clearScreenButtonActionPerformed

    private void lineRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineRadioActionPerformed
        mySketchPanel.setItemType( DrawItem.LINE );
    }//GEN-LAST:event_lineRadioActionPerformed

    private void freehandRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freehandRadioActionPerformed
        mySketchPanel.setItemType( DrawItem.FREEHAND );
    }//GEN-LAST:event_freehandRadioActionPerformed

    private void filledRectangleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filledRectangleRadioActionPerformed
        mySketchPanel.setItemType( DrawItem.OPEN_RECTANGLE );
    }//GEN-LAST:event_filledRectangleRadioActionPerformed

    private void closedRectangleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closedRectangleRadioActionPerformed
        mySketchPanel.setItemType( DrawItem.FILLED_RECTANGLE );
    }//GEN-LAST:event_closedRectangleRadioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SketchPad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SketchPad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SketchPad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SketchPad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SketchPad().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton circleRadio;
    private javax.swing.JButton clearScreenButton;
    private javax.swing.JRadioButton closedRectangleRadio;
    private javax.swing.JRadioButton filledRectangleRadio;
    private javax.swing.JRadioButton freehandRadio;
    private javax.swing.JPanel itemPicker;
    private javax.swing.JRadioButton lineRadio;
    private foo.SketchPanel mySketchPanel;
    private javax.swing.JButton setPenColorButton;
    private javax.swing.JRadioButton starRadio;
    // End of variables declaration//GEN-END:variables
}
