/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foo;

import java.util.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author grant
 */
public class SketchPanel extends javax.swing.JPanel {
private java.util.List itemsToDraw = new ArrayList();
    /**
     * Creates new form SketchPanel
     */
    public SketchPanel() {
        initComponents();
        setBackground( java.awt.Color.white );
        initComponents();
        this.setCursor( new Cursor( Cursor.CROSSHAIR_CURSOR ) );

    }

    public void paintComponent( Graphics g ) {
        super.paintComponent( g );
        g.setColor( Color.BLACK );
        Iterator thisPoint = itemsToDraw.iterator();
        Point last = null;
        while ( thisPoint.hasNext() ) {
            Point p = (Point) thisPoint.next();
            if ( last != null )
                g.drawLine( last.x, last.y, p.x, p.y );
            last = p;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = new Point( evt.getX(), evt.getY() );
        itemsToDraw.add( p );
        repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
